# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f16ff697c65534e98b0ed5486af11834"
name = "node-app"
application_url = "https://donations-penn-smithsonian-centres.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "zingbbt.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://donations-penn-smithsonian-centres.trycloudflare.com/auth/callback",
  "https://donations-penn-smithsonian-centres.trycloudflare.com/auth/shopify/callback",
  "https://donations-penn-smithsonian-centres.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
